CREATE TABLE IF NOT EXISTS YOUTUBE_LIST (
      IDX INT AUTO_INCREMENT PRIMARY KEY,
      PUBLISHED_AT VARCHAR(20),
      CHANNEL_ID VARCHAR(20),
      VIDEO_ID VARCHAR(20),
      TITLE VARCHAR(200),
      DESCRIPTION VARCHAR(400),
      CHANNEL_TITLE VARCHAR(90),
      THUMBNAIL_URL VARCHAR(100)
);